add interactions yaml and update extract_usage
Lattice-Works/chronicle-analysis pull request #10
Opened 2020-02-21 20:01 UTC by nicholashobbs

https://jira.openlattice.com/browse/INTEGRATE-687
https://jira.openlattice.com/browse/INTEGRATE-688
https://jira.openlattice.com/browse/INTEGRATE-873

2020-02-22 01:12 UTC, nicholashobbs commented
added fix for this https://jira.openlattice.com/browse/INTEGRATE-690

2020-02-26 00:03 UTC, jokedurnez requested changes
Couple smaller issues

2020-02-26 00:03 UTC, jokedurnez commented on chroniclepy/src/preprocessing.py
> +import ruamel.yaml as yaml
Can you add this dependency here: https://github.com/Lattice-Works/chronicle-analysis/blob/72dedec4b1320f546033cab20425e563fe8439d9/Dockerfile#L16
So that the docker file has all the necessary dependencies.

2020-02-26 00:03 UTC, jokedurnez commented on chroniclepy/src/preprocessing.py
> +        outtime = [{
This still needs participant_id and app_fullname.

2020-02-26 00:03 UTC, jokedurnez commented on chroniclepy/src/preprocessing.py
> +    if prevtime:
maybe change this into 
```
if not prevtime:
    <do something>
    return pd.DataFrame(something)
<add the rest unindented>
```

To prevent this whole function to be indented based on the boolean

2020-02-26 19:53 UTC, nicholashobbs commented on chroniclepy/src/preprocessing.py
> +import ruamel.yaml as yaml
used import yaml instead - it has the same safe_load function that works identically and dependency already exists

2020-02-26 19:57 UTC, nicholashobbs commented on chroniclepy/src/preprocessing.py
> +    if prevtime:
done!

2020-02-26 19:57 UTC, nicholashobbs commented on chroniclepy/src/preprocessing.py
> +        outtime = [{
done

2020-02-26 20:00 UTC, jokedurnez approved these changes

2020-02-26 20:00 UTC, merged